apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: cluster2-m03
spec:
  asNumber: 64513
  nodeSelector: route-reflector == 'true'
  peerIP: ${CLUSTER2_M03_IP}
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: cluster2-m04
spec:
  asNumber: 64513
  nodeSelector: route-reflector == 'true'
  peerIP: ${CLUSTER2_M04_IP}
