apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: cluster1-m03
spec:
  asNumber: 64512
  nodeSelector: route-reflector == 'true'
  peerIP: ${CLUSTER1_M03_IP}
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: cluster1-m04
spec:
  asNumber: 64512
  nodeSelector: route-reflector == 'true'
  peerIP: ${CLUSTER1_M04_IP}
