apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: disabled-podcidr-for-clustera
spec:
  cidr: 10.200.0.0/16
  disabled: true
  natOutgoing: false
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: disabled-servicecidr-for-clustera
spec:
  cidr: 10.201.0.0/16
  # Prevent an IP pool from being used automatically by Calico IPAM, while still allowing it to be used manually for static assignments
  nodeSelector: !all()  
  natOutgoing: false
